### PR TITLE
Add "Coding Machines"

### PR DESCRIPTION
**Pull request by NieDzejkob**
I'm having a hard time coming up with the right title, as it seems like the story is extremely susceptible to spoilers.

### CODE REVIEW

**Comment by NieDzejkob** [comment]
Lint failure because of preexisting links, I suppose there's no point to correct it?

**Comment by klaernie** [comment]
It's a fascinating story, but I would assume it's fiction. I  personally wouldn't feel good mixing fiction into all the other stories based on facts.

**Comment by rask** [comment]
@klaernie would a wholly separate section for fiction be okay?

**Comment by klaernie** [comment]
@rask yeah, that sounds like a good idea to me.

**Comment by NieDzejkob** [comment]
I have pushed some commits that move the story to a separate fiction section.

**Comment by bgianfo** [comment]
Thanks!

**Pull request merged**
